from pathlib import Path
from snakemake.utils import min_version


# Configuration
configfile: "config/config.yaml"


# Define modules
module tables:
    snakefile:
        "rules/tables.smk"
    config:
        config


# Load modules
use rule * from tables as tables_*


# ----------- #
#  Workflow   #
# ----------- #


rule all:
    input:
        rules.tables_all.input,
    default_target: True
