# -------------- #
#    Workflow    #
# -------------- #

FILEPATHS:
  INSTALL_DIRS:
    BIN: resources/bin
    DATA: resources/data
  PROCESS_DIRS: 
    TABLES: results/tables
  BENCHMARK_DIR: workflow/benchmarks
  LOG_DIR: workflow/logs

URLS:
  ENCODE:
    SCREEN:
      V4:
        CCRES: https://downloads.wenglab.org/Registry-V4/GRCh38-cCREs.bed
        GENE_LINKS: https://downloads.wenglab.org/Human-Gene-Links.zip
        GENE_NEAREST: https://downloads.wenglab.org/GRCh38-Closest-Genes-PC.tsv
        CTCF_ZSCORES: https://www.encodeproject.org/files/ENCFF392IXG/@@download/ENCFF392IXG.txt.gz
        DNASE_ZSCORES: https://www.encodeproject.org/files/ENCFF397LSK/@@download/ENCFF397LSK.txt.gz

RESOURCES:
  ENCODE: 
    SCREEN:
      V4:
        /panfs/accrepfs.vampire/data/ruderferlab/projects/ctcf/resources/data/encode/screen/v4
  GENCODE:
    V40:
      GTF:
        /panfs/accrepfs.vampire/data/ruderferlab/projects/ctcf/resources/data/gencode/v40/gencode.v40.annotation.gtf.gz


# -------------- #
#    Cluster     #
# -------------- #

# Resources for a job run on a cluster
CLUSTER:
  RESOURCES:
    RULE_X:
      RUNTIME: # In minutes
      MEMORY_MB: X
      TIME: X

# Defaults - applied to all rules
__default__:
  account: X
  output: workflow/logs/{rule}-{wildcards}.out
  error: workflow/logs/{rule}-{wildcards}.out